name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: yuyinws/yuyinws.github.io@build
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: yuyinws/yuyinws.github.io
        TARGET_BRANCH: build
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: ./
