name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: yuyinws/yuyinws.github.io@build
      env:
        ACCESS_TOKEN: 6887ff7c5c19d124b1d21959dd0d819f3700fdde
        TARGET_REPO: yuyinws/yuyinws.github.io
        TARGET_BRANCH: buld
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: ./
